### ISSUE TITLE
"Administrator" typo

### ISSUE THREAD

**Issue by AntoineKamel** [judsonmitchell/ClinicCases#1]
Hi. In the source code of ClinicCases 7.1.3, there is a typo in "Administrator" in some files, showing as "Adminstrator".

*For example*, in "_INSTALL/default.sql", line 434;
and in "newaccount\index.php", line 39.

**Thanks!**

**Comment by judsonmitchell** [comment]
Thanks for pointing this out. Fixed in [50c1597](https://github.com/judsonmitchell/ClinicCases/commit/50c1597cbe3a3683f72558747161c300a01c96b5)
