### ISSUE TITLE
ignore

### ISSUE THREAD

**Issue by jwperkins1** [judsonmitchell/ClinicCases#30]
fixed error

**Comment by MAJOR2LAW** [comment]
how did you manage. I was waiting for help as well.

**Comment by MAJOR2LAW** [comment]
I have created subdomain for cliniccases and extracted the installation files to the home of the subdomain. im stuck on "Sorry, it appears that the path to documents you specified (/var/cc_docs) either does not exist or is not writable. Please fix this and try again."

**Comment by jwperkins1** [comment]
Oh my apologies I should have left it then. My fix was I made a separate network drive then mapped it to that. It might not be a good fix but it worked for me.

**Comment by jwperkins1** [comment]
@MAJOR2LAW Did it work for you?

**Comment by MAJOR2LAW** [comment]
Nope, see issue No.32
