### ISSUE TITLE
installation on a subdomain

### ISSUE THREAD

**Issue by MotlatsoLaw** [judsonmitchell/ClinicCases#32]
I created a subdomain.
created a folder named cliniccases in the home directory of the subdomain.
I downloaded the zip source package from Github uploaded same in folder of cliniccases and extracted inside.
I then created another folder for var in the subdomain but outside the cliniccases folder.
I created a folder named cc_docs in the var folder and set the permission writable (777 ).
I created another folder named www in var folder and then cliniccases in www folder.

I still get the message "Sorry, it appears that the path to documents you specified (/var/cc_docs) either does not exist or is not writable. Please fix this and try again". 

Please help

**Comment by jwperkins1** [comment]
Are you trying this on an actual server or a virtual server? I solved this issue on a virtual machine running windows and wamp. What I had to do was set the cc_docs folder as a separate network drive then map it out and share it. Once that was done I just pointed the virtual server to that drive and it worked for me. Then I ran into another issue after that but the above is how I got around that prior issue.

**Comment by judsonmitchell** [comment]
Do you have command line access to your server? If so, navigate to your cc_docs folder and then issue the command "pwd".  The output of that command is what should go in your config.

A different issue is your directory structure and I'm not quite clear how you have it setup. Generally, the source code should be extracted to a directory that is viewable on the web (the web root). So, for example, on a Linux box that would be something like:

/var/www/html/cliniccases

The cc_docs folder must be outside of the web of the web root, which in this example would be:

/var/cc_docs

cc_docs does not need to be 777. The only user who needs to read and write to it is the web server. Giving all permissions on that folder (777) creates a security problem.

Hope that helps.

**Comment by MAJOR2LAW** [comment]
Thank you, 

I will have to work on my web server to configure Apache.

Will close the ticket once I have fully installed the application.

Thank you again
