### ISSUE TITLE
make print "case data" to be better

### ISSUE THREAD

**Issue by test2a** [judsonmitchell/ClinicCases#33]
the current "print" option in the case data tab is not good because it gives you a single line multi page document which is difficult to read. we can just as easily create 2 or even 3 columns and put the entire data in a single page.

**Comment by test2a** [comment]
@ninahorne hey, not to bother you much but you've been working quite a lot of V8. is there a demo or something we can get to check and test the new update so that people can suggest improvements/find bugs?

**Comment by ninahorne** [comment]
Hey! I'm still chugging along on these planned updates. Not quite ready for
a QA session, but would definitely share it when it's ready to get as many
eyes as possible on it.

**Comment by test2a** [comment]
@ninahorne hey. Sorry to bother you but how are the updates going?  Any news on when we can expect a beta update? Alpha? Any screenshots? 

Any work on fixing issues?

**Comment by ninahorne** [comment]
Hey! Yes I know it’s been taking me a while. The big thing that I’ve been working on is a total redesign of the UI. It’s required quite a bit of server work as well and is taking me a lot longer than I’d originally thought (I was fairly new to php when I started this project), and my workload at my actual job has gotten a lot higher making it harder to contribute more than a couple of hours a week. 

That being said, I can certainly see the finish line. I’m happy to provide some screen shots for you next week. When I’m finished with my updates, I will very much need some testers to provide lots of feedback and would appreciate your help there for sure. 


As far as issues, I haven’t been keeping track of open issues but I’m happy to take a look and see if either I have either already fixed some with the update or if I can add them in. 

Thanks for your patience! I’m hoping it’ll be worth the wait :)

**Comment by test2a** [comment]
@ninahorne thats super awesome. i'd be very glad to test it out.  

one thing, a lot of the current issues are around installation. Have you thought about adding the application, once its ready to be added to softaculous and other 1click install repos? that way a user doesnt have to manually install anything. just click install and get a working copy ready everytime. Like wordpress or other softwares do. That would be a huge thing for people who can't really fight bugs. 

That said, i have a pull request pending, for the past 2 odd years. can you see if that is still needed and merge that in the updated version if yours doesn't have it? 

i had a couple other fixes but sadly in the interim, i lost access to the installation due to a server crash so i never copied those updates. will try to recreate them if those bugs still crop up

**Comment by test2a** [comment]
@ninahorne  ooo.. this looks slick. nice work.... 

about installation, there are a bunch #29, #20 #31, and a bunch of others.


i had made a bunch of feature requests, can you close the ones you think you've fixed or implemented or otherwise are not relevant? like #33 or or #42


basically you can go through each issue, close which is not relevant or is fixed with your work so that we know where we currently stand. 

we can do one more thing, i can buy and spin up a shared hosting for you. you can install your dev work or i will try to install version8 branch and see if that works or not. is my PR necessary now or not? 

i am looking forward to using the updated software so yeah. thanks again

**Comment by ninahorne** [comment]
This will be addressed in version 8
