### ISSUE TITLE
Customize Tabs

### ISSUE THREAD

**Issue by MotlatsoLaw** [judsonmitchell/ClinicCases#35]
Hello Everyone 

I have successfully installed cliniccases on the server. The challenges I have are as follows:

1. I have tempered with allowed_tabs on my groups and the tabs disappeared. I was trying to ad certain tabs in other groups. **Please share the defaults allowed_tabs for all groups.**
2. I have customized the casenumbers to my files style (MA0001) and that caused all files to be marked as closed. **How do I use casenumber of that format without getting the files closed?**
3. Lastly is there a easier way to import cases in bulk?

Thank you all in advance.
Im really enjoying the application.

**Comment by test2a** [comment]
What tabs do you want hidden or shown? In my use, I found users with different acl /roles have different access to tabs.

**Comment by MotlatsoLaw** [comment]
I need all defaults allowed_tabs (admin, professor, students & super). i tempered with them and now they dont show. see attached
![Screenshot 2022-05-17 at 20 13 16](https://user-images.githubusercontent.com/70703967/168882873-e3f23ff9-62fa-4324-b703-55b7d4026ad0.png)
.

**Comment by test2a** [comment]
Why don't you create users with super permission or admin ?  It would be much easier than editing the code

**Comment by MotlatsoLaw** [comment]
The problem is played around with the values of the  allowed_tab on all groups(see the highlighted block in the previous screenshort). If I create new users i am of the view that they will definitely use the wrong values). if you dont mind please share with me the default values of the allowed_tabs for all groups. i will copy them and paste problem will be solved.

**Comment by MotlatsoLaw** [comment]
**The cliniccases website only has the default values for administrator (see below).**

The "allowed_tabs" field in the cm_groups controls which tabs the users in a particular group see. This field is a serialized array of permitted tab names. The possible permitted tabs are: Home, Cases, Group, Users, Utilities, Board, Journals, and Messages. So, for example, the allowed_tabs for administrators by default is:

a:6:{i:0;s:4:"Home";i:1;s:5:"Cases";i:2;s:5:"Users";i:3;s:5:"Board";i:4;s:9:"Utilities";i:5;s:8:"Messages";}

**Comment by test2a** [comment]
https://github.com/judsonmitchell/ClinicCases/blob/b9ad8898832d25bbd17f97bca7e82f553f20b2b1/_INSTALL/default.sql#L433

check this link for "super user" permissions. this should help

**Comment by MotlatsoLaw** [comment]
Thank you so much.
I have customized the casenumbers to my files style (MA0001) and that caused all files to be marked as closed. How do I use casenumber of that format without getting the files closed?

**Comment by test2a** [comment]
https://cliniccases.com/documentation/#!customization.md


this has case number customization but i have never tried that myself...

how was your experience in installing the software? what php did you use?

what was your location of data folder? 

"/var/cc_docs"?

"../cc_docs?"

**Comment by MotlatsoLaw** [comment]
I took me some time because a i was not following instructions but I once i followed each and every instruction it went  smooth. My data folder is on /var/cc_docs .

**Comment by test2a** [comment]
@MotlatsoLaw thats great... the team here has been building V8 for quite some time now so i guess we will see that in some time....

do you think we should improve some stuff, documentation or other patches? i mean i had to fork the code when i found i need to add magic quotes and other small stuff. 

things like uploading a file does not always work, what do you think?

**Comment by MotlatsoLaw** [comment]
This application is very good but indeed there is room for Improvement. I am new to it but so far so good. What I would like to see in future is the following:

1. billing 
2. sms 

At this stage when I login to the application using safari I don't see any cases  or sometimes if I do, I found them under closed files whereas when I login to the application with Mozilla Firefox all file appear and under open files. Im not sure what is the cause. I was of the view that me changing case number manually to a different type format was the cause but only on safari. But I will keep on updating you of the things I see. That's all for now.
