### ISSUE TITLE
Build process

### ISSUE THREAD

**Issue by jameskraus** [judsonmitchell/ClinicCases#5]
What's the process for building the .min.js files?

**Comment by jameskraus** [comment]
If there isn't a build process, I'd be happy to write a quick webpack config for them.

**Comment by bschoenfeld** [comment]
@jameskraus I'm wondering the same thing. Did you close this because you figured it out?

**Comment by jameskraus** [comment]
@bschoenfeld, nope, never figured this out.

**Comment by judsonmitchell** [comment]
Sorry for the delay.  There is no automated build process as such, I just use uglify on all scripts related to a page and output a minified bundle. E.g,

```
uglifyjs Cases.js cases* -o cases.min.js --source-map Cases.map
```
